---
apiVersion: v1
kind: Service
metadata:
  name: mongodb0
spec:
  selector:
    app: mongodb0
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    nodePort: 31100
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb1
spec:
  selector:
    app: mongodb1
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    nodePort: 31101
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb2
spec:
  selector:
    app: mongodb2
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    nodePort: 31102
  type: NodePort